name: Terraform CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v0.1.0

      - name: Run a Terraform init (v0.12)
        uses: docker://hashicorp/terraform:0.12.30
        with:
          entrypoint: terraform
          args: init

      - name: Run a Terraform validate (v0.12)
        uses: docker://hashicorp/terraform:0.12.30
        with:
          entrypoint: terraform
          args: validate

      - name: Run a Terraform init (v0.13)
        uses: docker://hashicorp/terraform:0.13.6
        with:
          entrypoint: terraform
          args: init

      - name: Run a Terraform validate (v0.13)
        uses: docker://hashicorp/terraform:0.13.6
        with:
          entrypoint: terraform
          args: validate

      - name: Run a Terraform init (v0.14)
        uses: docker://hashicorp/terraform:0.14.6
        with:
          entrypoint: terraform
          args: init

      - name: Run a Terraform validate (v0.14)
        uses: docker://hashicorp/terraform:0.14.6
        with:
          entrypoint: terraform
          args: validate
